### ISSUE TITLE
Update KDE Runtime to v5.15-21.08

### ISSUE THREAD

**Issue by proletarius101** [flathub/eu.ad5001.LogarithmPlotter#7]
Since the 5.15 runtime has been end-of-life, can you upgrade it to the latest stable runtime? @Ad5001 

Example: https://github.com/flathub/org.onionshare.OnionShare/pull/4

**Comment by Ad5001** [comment]
I'm currently working on it for v0.2.0. I need to test it some more however.

**Comment by Ad5001** [comment]
Updated in the latest commit.
